<<<<<<< HEAD
#O bloco finally exceção ter ocorrido ou não:
try:
    x = 10 / 0
except ZeroDivisionError as e:
    print(f"Erro de divisão por zero: {e}")
finally:
    print("Este bloco é sempre executado.")
=======
#O bloco finally exceção ter ocorrido ou não:
try:
    x = 10 / 0
except ZeroDivisionError as e:
    print(f"Erro de divisão por zero: {e}")
finally:
    print("Este bloco é sempre executado.")
>>>>>>> 08b2136512fad3bd18765b823f223fa35b93a67d
